name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.1"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Lint
        run: poetry run ruff check .
      - name: Type check
        run: poetry run mypy src tests
      - name: Test
        run: poetry run pytest
