name: Publish to PyPI
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry
      - name: Build & publish
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config virtualenvs.create false
          poetry install --without dev docs --no-interaction
          poetry build
          poetry publish --username "$POETRY_HTTP_BASIC_PYPI_USERNAME" --password "$POETRY_HTTP_BASIC_PYPI_PASSWORD"